stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/AVN_Basic.csv
      - params.yaml
    params:
      - data
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train.csv
      - data/processed/test.csv
      - params.yaml
    params:
      - models
      - features
    outs:
      - models/vectorizer.pkl
      - models/champion_model.pkl
      - models/champion_name.txt