apiVersion: v1
kind: Service
metadata:
  name: phishing-classifier-service
spec:
  selector:
    app: phishing-classifier
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30800